### ISSUE TITLE
Custom aliases in dctl.yml

### ISSUE THREAD

**Issue by jutonz** [jutonz/dctl_rb#5]
As a user I would like to be able to add aliases to commonly used commands in my `.dctl.yml` file.

For instance, if there is a sequence of commands I do to migrate a database, I could add something like this:

```yml
aliases:
  migrate:
  - dctl run --rm psql initdb
  - dctl run --rm app mix ecto.seed
```
